CONFIG_CBPRINTF_FP_SUPPORT=y # For printing floats with printk
CONFIG_STDOUT_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_PWM=y
CONFIG_SENSOR=y
CONFIG_COUNTER=y
CONFIG_CAN=y
CONFIG_CAN_FD_MODE=y
CONFIG_CAN_STM32_FDCAN=y
