CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_STDOUT_CONSOLE=y
CONFIG_PWM=y
CONFIG_SENSOR=y
CONFIG_COUNTER=y
CONFIG_CAN=y
CONFIG_CAN_FD_MODE=y
CONFIG_CAN_STM32_FDCAN=y
CONFIG_GPIO=y
CONFIG_SPI=y
CONFIG_LED_STRIP=y
CONFIG_WS2812_STRIP_SPI=y
CONFIG_CBPRINTF_FP_SUPPORT=y
#CONFIG_UART_ASYNC_API=y
#CONFIG_UART_INTERRUPT_DRIVEN=n
